import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Bell,
  ShieldAlert,
  AlertTriangle,
  Clock,
  ArrowRight,
  GitFork,
  MapPin,
  Sparkles,
  RefreshCw,
  Filter
} from 'lucide-react';
import { api } from '../services/api';
import { AlertItem } from '../types';
import { RiskBadge } from '../components/RiskBadge';

export const Alerts: React.FC = () => {
  const [alerts, setAlerts] = useState<AlertItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedSeverity, setSelectedSeverity] = useState<string>('ALL');
  const navigate = useNavigate();

  const loadAlerts = async () => {
    try {
      setLoading(true);
      const data = await api.getAlerts();
      setAlerts(data);
    } catch (e) {
      console.error('Failed to load alerts:', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, []);

  const filtered = alerts.filter(
    (a) => selectedSeverity === 'ALL' || a.severity === selectedSeverity
  );

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2.5">
            <h2 className="text-2xl font-extrabold text-slate-900 tracking-tight">
              Intelligence Alerts
            </h2>
            <span className="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-bold bg-rose-100 text-rose-700">
              <Sparkles className="w-3.5 h-3.5" />
              Automated Forensic Triggers
            </span>
          </div>
          <p className="text-sm text-slate-500 mt-0.5 font-medium">
            Real-time cybercrime alerts generated by velocity thresholds, smurfing patterns, and NCRP complaints.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="flex items-center gap-1 p-1 bg-surface-bg rounded-2xl border border-slate-200">
            {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM'].map((sev) => (
              <button
                key={sev}
                onClick={() => setSelectedSeverity(sev)}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                  selectedSeverity === sev
                    ? 'bg-white text-brand-700 shadow-xs'
                    : 'text-slate-500 hover:text-slate-800'
                }`}
              >
                {sev}
              </button>
            ))}
          </div>

          <button
            onClick={loadAlerts}
            className="p-2 rounded-xl bg-white border border-slate-200 text-slate-600 hover:text-slate-900 transition-colors shadow-xs"
            title="Refresh Alerts"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* Alerts List */}
      <div className="space-y-3.5">
        {loading ? (
          <div className="py-20 text-center text-slate-400">
            <RefreshCw className="w-6 h-6 animate-spin mx-auto mb-2 text-brand-600" />
            <p className="text-xs font-bold">Fetching latest intelligence alerts...</p>
          </div>
        ) : filtered.length > 0 ? (
          filtered.map((alert) => (
            <div
              key={alert.id}
              className="bg-white rounded-2xl border border-surface-border p-5 shadow-soft hover:shadow-card transition-all flex flex-col md:flex-row md:items-center justify-between gap-4"
            >
              <div className="flex items-start gap-4">
                <div
                  className={`w-11 h-11 rounded-xl flex items-center justify-center flex-shrink-0 mt-0.5 ${
                    alert.severity === 'CRITICAL'
                      ? 'bg-rose-50 text-rose-600'
                      : alert.severity === 'HIGH'
                      ? 'bg-orange-50 text-orange-600'
                      : 'bg-amber-50 text-amber-600'
                  }`}
                >
                  <ShieldAlert className="w-5 h-5" />
                </div>

                <div>
                  <div className="flex flex-wrap items-center gap-2.5">
                    <h4 className="text-sm font-extrabold text-slate-900">
                      {alert.alert_type.replace(/_/g, ' ')}
                    </h4>
                    <RiskBadge level={alert.severity} />
                    <span className="text-xs font-bold text-slate-500 bg-slate-100 px-2 py-0.5 rounded-md">
                      {alert.account_number} • {alert.account_name}
                    </span>
                  </div>

                  <p className="text-xs text-slate-600 font-medium mt-1.5 leading-relaxed">
                    {alert.reason}
                  </p>

                  <div className="flex items-center gap-2 text-[11px] text-slate-400 mt-2 font-medium">
                    <Clock className="w-3.5 h-3.5" />
                    <span>Logged at {new Date(alert.created_at).toLocaleString()}</span>
                  </div>
                </div>
              </div>

              {/* Quick Investigation Shortcuts */}
              <div className="flex items-center gap-2 self-end md:self-auto flex-shrink-0">
                <button
                  onClick={() => navigate(`/money-flow?account_id=${alert.account_id}`)}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-surface-bg hover:bg-slate-100 text-slate-700 text-xs font-bold transition-colors"
                >
                  <GitFork className="w-3.5 h-3.5 text-brand-600" />
                  <span>Money Flow</span>
                </button>

                <button
                  onClick={() => navigate(`/geo?account_id=${alert.account_id}`)}
                  className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-brand-600 hover:bg-brand-700 text-white text-xs font-bold shadow-xs transition-colors"
                >
                  <MapPin className="w-3.5 h-3.5" />
                  <span>Track Cash-Out</span>
                  <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            </div>
          ))
        ) : (
          <div className="py-16 text-center text-slate-400 bg-white rounded-3xl border border-surface-border">
            No alerts found for the selected filter.
          </div>
        )}
      </div>
    </div>
  );
};
